ARG BASE_IMAGE=22.04
FROM ubuntu:${BASE_IMAGE} AS build

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    cmake g++ build-essential ccache && \
    rm -rf /var/lib/apt/lists/*

ENV CCACHE_DIR=/build/.ccache \
    CCACHE_COMPILERCHECK=content

ARG BASE_IMAGE
RUN --mount=type=cache,id=ccache-${BASE_IMAGE},target=/build/.ccache,sharing=locked \
    --mount=target=/DockerSandbox,rw \
        /DockerSandbox/ci/build.sh /DockerSandbox/ /build
